config/routes.rb
Haikuary::Application.routes.draw do

  get :ping, to: "application#ping"
  resources :haikus  do
    get :random, on: :collection
  end

  resources :searches, only: :index, path: 'search'

  root to: 'haikus#index'

end

app/models/haiku.rb
class Haiku < ActiveRecord::Base
  validate :word_count_less_than_18
  validate :well_formed
  validates :description, presence: true, uniqueness: true
  validate :formation
  validates_uniqueness_of :description
  before_save :tag_haiku
  scope :not_generated, -> { where.not(author: 'Happy Haiku Bot') }

  def self.get_random
    scope = Haiku.not_generated
    random_id = rand(scope.count).to_i
    haiku = scope.find_by(id: random_id)
    haiku ? haiku : get_random
  end

private

  def tag_haiku
    HaikuTagger.new(self).tag_haiku
  end

  def word_count_less_than_18
    errors[:description] << "too many words" if description.split.size > 17
  end

  def dissect_line(line)
    SyllableCounter::Count.new.get_syllables(line)
  end

  def well_formed
    description.lines.each_with_index do |line, index|
      count = dissect_line(line)
      if ((valid_syllables_for_line(index) - count).abs > 1)
        errors[:description] << "wrong number of syllables on line #{index+1}"
      end
    end
  end

  def formation
    errors[:description] << "Please use 3 lines." unless description.lines.count == 3
  end

  def valid_syllables_for_line(index)
    framing = [5,7,5]
    framing[index] || 0
  end
end

app/controllers/haikus_controller.rb
class HaikusController < ApplicationController
  before_filter :load_resource, only: [ :show ]

  def index
    @haikus = Haiku.not_generated.order(id: :desc).page(params[:page]).per_page(20)
    respond_with @haikus
  end

  def show
  end

  def new
    @haiku = Haiku.new
    respond_with @haiku
  end

  def create
    @haiku = Haiku.create(haiku_params)
    respond_with @haiku
  end

  def random
    @haiku = HaikuMaker::Base.new.result
    @haiku ||= Haiku.new(description: "Empty database\nWhat happened to me, I'm lost\n without my data.")
    respond_with @haiku
  end

private

  def load_resource
    @haiku = Haiku.find(params[:id])
  end

  def haiku_params
    params.require(:haiku).permit(:description, :author)
  end
end

app/helpers/haiku_helper.rb
module HaikuHelper
  def twitter_description(haiku)
    haiku.description
  end
end

app/views/haikus/_haiku.html.erb
<div class="pretty_haiku haiku_#{haiku.id}" id="#{haiku.id}">
  <div class="haiku">
    <%= simple_format haiku.description %>
    <div class="author">
      <%= simple_format haiku.author %>
    </div>
  </div>
</div>

app/views/haikus/index.html.erb
<div id="haikus">
  <%= render partial: "haikus/haiku", collection: @haikus %>
</div>
<% if @haikus.respond_to?(:total_pages) %>
  <div class="center">
    <%= will_paginate @haikus %>
  </div>
<% end %>

app/views/haikus/new.html.erb
<%= simple_form_for :haiku do |f| %>
  <%= f.input :description, as: :text, input_html: { rows: 3 }, autofocus: true %>
  <%= f.input :author %>
  <%= f.submit class: "btn btn-primary center" %>
<% end %>

app/views/haikus/random.html.erb
<div id="haiku">
  <%= render partial: "haiku", locals: { haiku: @haiku } %>
</div>

<div class="form_page">
  <%= simple_form_for @haiku, url: haikus_path do |f| %>
    <div class="hide">
      <%=f.input :description, as: :text, input_html: {rows: 3} %>
      <%=f.input :author, as: :hidden %>
    </div>
    <%=f.submit "Submit magic haiku", class: "btn btn-primary center" %>
  <% end %>
</div>

app/views/haikus/show.html.erb
<%= render partial: "haiku", locals: { haiku: @haiku } %>