config/routes.rb
Haikuary::Application.routes.draw do

  get :ping, to: "application#ping"
  resources :haikus  do
    get :random, on: :collection
  end

  resources :searches, only: :index, path: 'search'

  root to: 'haikus#index'

end

app/views/layouts/_errors.html.erb
<div id="flash" %>
  <% if flash[:notice] %>
    <div class="alert alert-success center">
      <%= flash[:notice] %>
    </div>
  <% end %>

  <% if flash[:error] %>
    <div class="alert alert-error center">
      <%= flash[:error] %>
    </div>
  <% end %>

app/views/layouts/_header.html.erb
<div class="navbar-top">
  <div class="navbar-inner">
    <%= link_to "Haiku d'etat", root_path, class: "page_title" %>
    <div class="haiku-left">
      <%= link_to "Generate Random Haiku", random_haikus_path, class: "btn btn-info" %>
    </div>
    <div class="haiku-right">
      <%= link_to "Create a Haiku", new_haiku_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<html lang: "en">
  <head>
    <title><%= t("title") %></title>
    <%= favicon_link_tag %>
    <%= favicon_link_tag 'apple-touch-icon.png', rel: 'apple-touch-icon', type: 'image/png' %>
    <meta property="description",  content="Haiku for fun, haiku for profit, haiku with friends">
    <meta property="og:title",     content="#{t('title')}">
    <meta property="og:site_name", content="#{t('title')}">
    <meta property="og:url",       content="http://www.haikudetat.com">
    <meta property="og:image",     content="http://www.haikudetat.com/haiku200.png">
    <link href='http://fonts.googleapis.com/css?family=Parisienne', rel='stylesheet'>
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no", name="viewport">

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= analytics_init if Rails.env.production? %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="content">
      <div id="messages">
        <%= render 'layouts/errors' unless flash.nil? %>
        <%= yield %>
      </div>
    </div>
    <div class="footer">
      <%= javascript_include_tag "application" %>
      <%= yield :footer %>
    </div>
  </body>
</html>